HEADER = "# 🚀 {name}'s Portfolio\n---\n"

FOOTER = """
---
### 📫 Contact
> 💡 **Tip**: LinkedIn 계정도 추가해보세요.
* **Email**: [🔗 {email}](mailto:{email})

---
*Generated by **POPOLO Agent** - Personal Activity Analysis Engine*
"""

def build_gallery_table(repos_info: list) -> str:
    table = "## 🏗 Project Gallery\n"
    table += "| 프로젝트 명 | 주요 스택 | 한 줄 요약 |\n"
    table += "| :--- | :--- | :--- |\n"
    for repo in repos_info:
        table += f"| {repo['name']} | {repo['stack']} | {repo['summary']} |\n"
    return table + "\n"

def assemble_full_portfolio(overview: str, gallery_table: str, project_sections: list) -> str:
    content = "\n\n".join(project_sections)
    return f"{HEADER}\n{overview}\n\n{gallery_table}\n\n{content}\n{FOOTER}"

async def save_to_file(content: str, filename: str="PORTFOLIO.md"):
    # 로컬 파일로 저장 (임시)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)